// Generated by com.hacknife.onlite.processor.OnLiteProcessor (https://github.com/hacknife/OnLite).
// If you have any questions in use, please use email to contact me (e-mail:4884280@qq.com).
package com.hacknife.onlite;

import android.content.ContentValues;
import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

public class TableDbLite extends OnLite<TableDb> {
    public TableDbLite() {
        tableName = "table_hacknife";
        version = 0;
    }

    @Override
    protected String createTable() {
        return "CREATE TABLE IF NOT EXISTS table_hacknife ("
                + "table varchar(255) DEFAULT NULL,"
                + "version INTEGER DEFAULT NULL)";
    }

    @Override
    protected TableDb createObject(Cursor cursor) {
        TableDb tableDb = new TableDb();
        tableDb.setTable(cursor.getString(cursor.getColumnIndex("table")));
        tableDb.setVersion(cursor.getInt(cursor.getColumnIndex("version")));
        return tableDb;
    }

    @Override
    protected ContentValues createContentValues(TableDb tableDb) {
        if (tableDb == null) return null;
        ContentValues values = new ContentValues();
        if (tableDb.getTable() != null)
            values.put("table", tableDb.getTable());
        if (tableDb.getVersion() != null)
            values.put("version", tableDb.getVersion());
        return values;
    }

    @Override
    protected String createSelection(TableDb where) {
        if (where == null) return null;
        StringBuilder builder = new StringBuilder();
        builder.append("1 = 1 ");
        if (where.getTable() != null)
            builder.append("and " + "table = ? ");
        if (where.getVersion() != null)
            builder.append("and " + "version = ? ");
        return builder.toString();
    }

    @Override
    protected String[] createSelectionArgv(TableDb where) {
        if (where == null) return null;
        List<String> list = new ArrayList<>();
        if (where.getTable() != null)
            list.add(String.valueOf(where.getTable()));
        if (where.getVersion() != null)
            list.add(String.valueOf(where.getVersion()));
        return list.toArray(new String[list.size()]);
    }
}