// Generated by com.hacknife.onlite.processor.OnLiteProcessor (https://github.com/hacknife/OnLite).
// If you have any questions in use, please use email to contact me (e-mail:4884280@qq.com).
package com.hacknife.onlite;

import android.content.ContentValues;
import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

public class TableDbLite extends OnLite<TableDb> {
    public TableDbLite() {
        tableName = "table_hacknife";
        version = 0;
    }

    @Override
    protected String createTable() {
        return "CREATE TABLE IF NOT EXISTS table_hacknife ("
                + "tableName varchar(255) DEFAULT NULL,"
                + "tableVersion INTEGER DEFAULT NULL)";
    }

    @Override
    protected TableDb createObject(Cursor cursor) {
        TableDb tableDb = new TableDb();
        tableDb.setTableName(cursor.getString(cursor.getColumnIndex("tableName")));
        tableDb.setTableVersion(cursor.getInt(cursor.getColumnIndex("tableVersion")));
        return tableDb;
    }

    @Override
    protected ContentValues createContentValues(TableDb tableDb) {
        if (tableDb == null) return null;
        ContentValues values = new ContentValues();
        if (tableDb.getTableName() != null)
            values.put("tableName", tableDb.getTableName());
        if (tableDb.getTableVersion() != null)
            values.put("tableVersion", tableDb.getTableVersion());
        return values;
    }

    @Override
    protected String createSelection(TableDb where) {
        if (where == null) return null;
        StringBuilder builder = new StringBuilder();
        builder.append("1 = 1 ");
        if (where.getTableName() != null)
            builder.append("and " + "tableName = ? ");
        if (where.getTableVersion() != null)
            builder.append("and " + "tableVersion = ? ");
        return builder.toString();
    }

    @Override
    protected String[] createSelectionArgv(TableDb where) {
        if (where == null) return null;
        List<String> list = new ArrayList<>();
        if (where.getTableName() !=null )
            list.add(String.valueOf(where.getTableName()));
        if (where.getTableVersion() !=null )
            list.add(String.valueOf(where.getTableVersion()));
        return list.toArray(new String[list.size()]);
    }
}